name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Pipeline Started"

      - run: echo "Running Tests"

      - run: echo "Pipeline Finished"
